replicaCount: 1

service:
  enabled: true
  type: ClusterIP
  port: 5000

auth:
  enabled: false

postgresql:
  enabled: false

mysql:
  enabled: false

backendStore:
  defaultSqlitePath: /tmp/mlflow.db
  databaseConnectionCheck: false
  databaseMigration: false

artifactRoot:
  defaultArtifactsDestination: /tmp/mlruns

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    memory: 768Mi

extraEnvVars:
  MLFLOW_DISABLE_ENV_MANAGER: "true"

image:
  repository: ghcr.io/mlflow/mlflow
  tag: v2.22.0

extraArgs:
  workers: "1"
  default-artifact-root: "/tmp/mlruns"